// This file is auto-generated by @hey-api/openapi-ts

export const UserLeaderboardSchemaSchema = {
  properties: {
    username: {
      title: "Username",
      type: "string",
    },
    games_won: {
      title: "Games Won",
      type: "integer",
    },
    joined_rooms: {
      title: "Joined Rooms",
      type: "integer",
    },
    win_rate: {
      title: "Win Rate",
      type: "number",
    },
  },
  required: ["username", "games_won", "joined_rooms", "win_rate"],
  title: "UserLeaderboardSchema",
  type: "object",
} as const;

export const ActivityFilterSchemaSchema = {
  properties: {
    actor_object_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Actor Object Id",
    },
    verb: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Verb",
    },
    action_object_object_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Action Object Object Id",
    },
    timestamp: {
      anyOf: [
        {
          format: "date-time",
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Timestamp",
    },
  },
  title: "ActivityFilterSchema",
  type: "object",
} as const;

export const ActivityResponseSchemaSchema = {
  properties: {
    id: {
      title: "Id",
      type: "integer",
    },
    verb: {
      title: "Verb",
      type: "string",
    },
    timestamp: {
      format: "date-time",
      title: "Timestamp",
      type: "string",
    },
    actor_object_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Actor Object Id",
    },
    action_object_object_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Action Object Object Id",
    },
    target_object_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Target Object Id",
    },
  },
  required: [
    "id",
    "verb",
    "timestamp",
    "actor_object_id",
    "action_object_object_id",
    "target_object_id",
  ],
  title: "ActivityResponseSchema",
  type: "object",
} as const;

export const MeResponseSchema = {
  properties: {
    id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "ID",
    },
    email: {
      maxLength: 254,
      title: "Email",
      type: "string",
    },
    username: {
      maxLength: 100,
      title: "Username",
      type: "string",
    },
    activities: {
      items: {
        $ref: "#/components/schemas/ActivityResponseSchema",
      },
      title: "Activities",
      type: "array",
    },
  },
  required: ["email", "username", "activities"],
  title: "MeResponse",
  type: "object",
} as const;

export const UserSchemaSchema = {
  properties: {
    id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "ID",
    },
    email: {
      maxLength: 254,
      title: "Email",
      type: "string",
    },
    username: {
      maxLength: 100,
      title: "Username",
      type: "string",
    },
  },
  required: ["email", "username"],
  title: "UserSchema",
  type: "object",
} as const;

export const AuthResponseSchema = {
  properties: {
    token: {
      title: "Token",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
    expiry: {
      format: "date-time",
      title: "Expiry",
      type: "string",
    },
  },
  required: ["token", "username", "expiry"],
  title: "AuthResponse",
  type: "object",
} as const;

export const UserLoginSchema = {
  properties: {
    email: {
      format: "email",
      title: "Email",
      type: "string",
    },
    password: {
      title: "Password",
      type: "string",
    },
  },
  required: ["email", "password"],
  title: "UserLogin",
  type: "object",
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      format: "email",
      title: "Email",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
    password: {
      title: "Password",
      type: "string",
    },
  },
  required: ["email", "username", "password"],
  title: "UserCreate",
  type: "object",
} as const;

export const RoomSchemaSchema = {
  properties: {
    id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "ID",
    },
    name: {
      anyOf: [
        {
          maxLength: 128,
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    game_type: {
      default: 0,
      title: "Game Type",
      type: "integer",
    },
    code_length: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 4,
      title: "Code Length",
    },
    num_of_colors: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 6,
      title: "Num Of Colors",
    },
    num_of_guesses: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 10,
      title: "Num Of Guesses",
    },
    secret_code: {
      anyOf: [
        {
          maxLength: 30,
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Secret Code",
    },
  },
  title: "RoomSchema",
  type: "object",
} as const;

export const CreateRoomSchemaSchema = {
  properties: {
    name: {
      anyOf: [
        {
          maxLength: 128,
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    game_type: {
      default: 0,
      title: "Game Type",
      type: "integer",
    },
    code_length: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 4,
      title: "Code Length",
    },
    num_of_colors: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 6,
      title: "Num Of Colors",
    },
    num_of_guesses: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 10,
      title: "Num Of Guesses",
    },
    created_by_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Created By",
    },
  },
  title: "CreateRoomSchema",
  type: "object",
} as const;
