// This file is auto-generated by @hey-api/openapi-ts

export const MeResponseSchema = {
  properties: {
    id: {
      title: "Id",
      type: "integer",
    },
    email: {
      title: "Email",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
  },
  required: ["id", "email", "username"],
  title: "MeResponse",
  type: "object",
} as const;

export const UserResponseSchema = {
  properties: {
    id: {
      title: "Id",
      type: "integer",
    },
    email: {
      title: "Email",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
  },
  required: ["id", "email", "username"],
  title: "UserResponse",
  type: "object",
} as const;

export const AuthResponseSchema = {
  properties: {
    token: {
      title: "Token",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
    expiry: {
      format: "date-time",
      title: "Expiry",
      type: "string",
    },
  },
  required: ["token", "username", "expiry"],
  title: "AuthResponse",
  type: "object",
} as const;

export const UserLoginSchema = {
  properties: {
    email: {
      format: "email",
      title: "Email",
      type: "string",
    },
    password: {
      title: "Password",
      type: "string",
    },
  },
  required: ["email", "password"],
  title: "UserLogin",
  type: "object",
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      format: "email",
      title: "Email",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
    password: {
      title: "Password",
      type: "string",
    },
  },
  required: ["email", "username", "password"],
  title: "UserCreate",
  type: "object",
} as const;

export const RoomSchemaSchema = {
  properties: {
    id: {
      title: "Id",
      type: "integer",
    },
    name: {
      title: "Name",
      type: "string",
    },
  },
  required: ["id", "name"],
  title: "RoomSchema",
  type: "object",
} as const;

export const RoomResponseSchema = {
  properties: {
    id: {
      title: "Id",
      type: "integer",
    },
    name: {
      title: "Name",
      type: "string",
    },
    type: {
      title: "Type",
      type: "integer",
    },
  },
  required: ["id", "name", "type"],
  title: "RoomResponse",
  type: "object",
} as const;

export const CreateRandomSingleplayerRoomRequestSchema = {
  properties: {
    code_length: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 4,
      title: "Code Length",
    },
    num_of_colors: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 6,
      title: "Num Of Colors",
    },
    num_of_guesses: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      default: 10,
      title: "Num Of Guesses",
    },
    type: {
      default: 0,
      title: "Type",
      type: "integer",
    },
  },
  title: "CreateRandomSingleplayerRoomRequest",
  type: "object",
} as const;

export const CheckBullsCowsResponseSchema = {
  properties: {
    bulls: {
      title: "Bulls",
      type: "integer",
    },
    cows: {
      title: "Cows",
      type: "integer",
    },
  },
  required: ["bulls", "cows"],
  title: "CheckBullsCowsResponse",
  type: "object",
} as const;

export const CheckBullsCowsRequestSchema = {
  properties: {
    room_id: {
      title: "Room Id",
      type: "integer",
    },
    guess: {
      title: "Guess",
      type: "string",
    },
  },
  required: ["room_id", "guess"],
  title: "CheckBullsCowsRequest",
  type: "object",
} as const;
