// This file is auto-generated by @hey-api/openapi-ts

import type {
  UsersApiGetUserActivitiesResponse,
  UsersApiLoginResponse,
  UsersApiSignupResponse,
} from "./types.gen";

const activityResponseSchemaSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

export const usersApiGetUserActivitiesResponseTransformer = async (
  data: any
): Promise<UsersApiGetUserActivitiesResponse> => {
  data = data.map((item: any) => {
    return activityResponseSchemaSchemaResponseTransformer(item);
  });
  return data;
};

const authResponseSchemaResponseTransformer = (data: any) => {
  data.expiry = new Date(data.expiry);
  return data;
};

export const usersApiLoginResponseTransformer = async (
  data: any
): Promise<UsersApiLoginResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};

export const usersApiSignupResponseTransformer = async (
  data: any
): Promise<UsersApiSignupResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};
