// This file is auto-generated by @hey-api/openapi-ts

import type {
  UsersApiLoginResponse,
  UsersApiSignupResponse,
} from "./types.gen";

const authResponseSchemaResponseTransformer = (data: any) => {
  data.expiry = new Date(data.expiry);
  return data;
};

export const usersApiLoginResponseTransformer = async (
  data: any
): Promise<UsersApiLoginResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};

export const usersApiSignupResponseTransformer = async (
  data: any
): Promise<UsersApiSignupResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};
