// This file is auto-generated by @hey-api/openapi-ts

/**
 * MeResponse
 */
export type MeResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
};

/**
 * AuthResponse
 */
export type AuthResponse = {
  /**
   * Token
   */
  token: string;
  /**
   * Username
   */
  username: string;
  /**
   * Expiry
   */
  expiry: Date;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
};

/**
 * RoomSchema
 */
export type RoomSchema = {
  /**
   * Name
   */
  name: string;
};

export type UsersApiMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/me";
};

export type UsersApiMeResponses = {
  /**
   * OK
   */
  200: MeResponse;
};

export type UsersApiMeResponse = UsersApiMeResponses[keyof UsersApiMeResponses];

export type UsersApiListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/";
};

export type UsersApiListUsersResponses = {
  /**
   * Response
   * OK
   */
  200: Array<UserResponse>;
};

export type UsersApiListUsersResponse =
  UsersApiListUsersResponses[keyof UsersApiListUsersResponses];

export type UsersApiGetUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/users/{user_id}";
};

export type UsersApiGetUserResponses = {
  /**
   * OK
   */
  200: UserResponse;
};

export type UsersApiGetUserResponse =
  UsersApiGetUserResponses[keyof UsersApiGetUserResponses];

export type UsersApiLoginData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type UsersApiLoginResponses = {
  /**
   * OK
   */
  200: AuthResponse;
};

export type UsersApiLoginResponse =
  UsersApiLoginResponses[keyof UsersApiLoginResponses];

export type UsersApiSignupData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/auth/signup";
};

export type UsersApiSignupResponses = {
  /**
   * OK
   */
  200: AuthResponse;
};

export type UsersApiSignupResponse =
  UsersApiSignupResponses[keyof UsersApiSignupResponses];

export type GamesApiListRoomsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/games/rooms";
};

export type GamesApiListRoomsResponses = {
  /**
   * Response
   * OK
   */
  200: Array<RoomSchema>;
};

export type GamesApiListRoomsResponse =
  GamesApiListRoomsResponses[keyof GamesApiListRoomsResponses];

export type GamesApiCreateRoomData = {
  body: RoomSchema;
  path?: never;
  query?: never;
  url: "/api/games/rooms";
};

export type GamesApiCreateRoomResponses = {
  /**
   * OK
   */
  200: RoomSchema;
};

export type GamesApiCreateRoomResponse =
  GamesApiCreateRoomResponses[keyof GamesApiCreateRoomResponses];

export type GamesApiGetRoomData = {
  body?: never;
  path: {
    /**
     * Room Id
     */
    room_id: number;
  };
  query?: never;
  url: "/api/games/rooms/{room_id}";
};

export type GamesApiGetRoomResponses = {
  /**
   * OK
   */
  200: RoomSchema;
};

export type GamesApiGetRoomResponse =
  GamesApiGetRoomResponses[keyof GamesApiGetRoomResponses];

export type ClientOptions = {
  baseUrl: string;
};
