// This file is auto-generated by @hey-api/openapi-ts

/**
 * ActivityFilterSchema
 */
export type ActivityFilterSchema = {
  /**
   * Actor Object Id
   */
  actor_object_id?: number | null;
  /**
   * Verb
   */
  verb?: string | null;
  /**
   * Action Object Object Id
   */
  action_object_object_id?: number | null;
  /**
   * Timestamp
   */
  timestamp?: Date | null;
};

/**
 * ActivityResponseSchema
 */
export type ActivityResponseSchema = {
  /**
   * Id
   */
  id: number;
  /**
   * Verb
   */
  verb: string;
  /**
   * Timestamp
   */
  timestamp: Date;
  /**
   * Actor Object Id
   */
  actor_object_id: number | null;
  /**
   * Action Object Object Id
   */
  action_object_object_id: number | null;
  /**
   * Target Object Id
   */
  target_object_id: number | null;
};

/**
 * UserSchema
 */
export type UserSchema = {
  /**
   * ID
   */
  id?: number | null;
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
};

/**
 * AuthResponse
 */
export type AuthResponse = {
  /**
   * Token
   */
  token: string;
  /**
   * Username
   */
  username: string;
  /**
   * Expiry
   */
  expiry: Date;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
};

/**
 * RoomSchema
 */
export type RoomSchema = {
  /**
   * ID
   */
  id?: number | null;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Game Type
   */
  game_type?: number;
  /**
   * Code Length
   */
  code_length?: number | null;
  /**
   * Num Of Colors
   */
  num_of_colors?: number | null;
  /**
   * Num Of Guesses
   */
  num_of_guesses?: number | null;
  /**
   * Secret Code
   */
  secret_code?: string | null;
};

/**
 * CreateRoomSchema
 */
export type CreateRoomSchema = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Game Type
   */
  game_type?: number;
  /**
   * Code Length
   */
  code_length?: number | null;
  /**
   * Num Of Colors
   */
  num_of_colors?: number | null;
  /**
   * Num Of Guesses
   */
  num_of_guesses?: number | null;
  /**
   * Created By
   */
  created_by_id?: number | null;
};

export type BncapiApiPingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/ping";
};

export type BncapiApiPingResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type UsersApiGetUserActivitiesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Actor Object Id
     */
    actor_object_id?: number | null;
    /**
     * Verb
     */
    verb?: string | null;
    /**
     * Action Object Object Id
     */
    action_object_object_id?: number | null;
    /**
     * Timestamp
     */
    timestamp?: Date | null;
  };
  url: "/api/users/activities";
};

export type UsersApiGetUserActivitiesResponses = {
  /**
   * Response
   * OK
   */
  200: Array<ActivityResponseSchema>;
};

export type UsersApiGetUserActivitiesResponse =
  UsersApiGetUserActivitiesResponses[keyof UsersApiGetUserActivitiesResponses];

export type UsersApiMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/me";
};

export type UsersApiMeResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type UsersApiListUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/";
};

export type UsersApiListUsersResponses = {
  /**
   * Response
   * OK
   */
  200: Array<UserSchema>;
};

export type UsersApiListUsersResponse =
  UsersApiListUsersResponses[keyof UsersApiListUsersResponses];

export type UsersApiGetUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/users/{user_id}";
};

export type UsersApiGetUserResponses = {
  /**
   * OK
   */
  200: UserSchema;
};

export type UsersApiGetUserResponse =
  UsersApiGetUserResponses[keyof UsersApiGetUserResponses];

export type UsersApiLoginData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type UsersApiLoginResponses = {
  /**
   * OK
   */
  200: AuthResponse;
};

export type UsersApiLoginResponse =
  UsersApiLoginResponses[keyof UsersApiLoginResponses];

export type UsersApiSignupData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/auth/signup";
};

export type UsersApiSignupResponses = {
  /**
   * OK
   */
  200: AuthResponse;
};

export type UsersApiSignupResponse =
  UsersApiSignupResponses[keyof UsersApiSignupResponses];

export type GamesApiListRoomsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/games/rooms";
};

export type GamesApiListRoomsResponses = {
  /**
   * Response
   * OK
   */
  200: Array<RoomSchema>;
};

export type GamesApiListRoomsResponse =
  GamesApiListRoomsResponses[keyof GamesApiListRoomsResponses];

export type GamesApiCreateRoomData = {
  body: CreateRoomSchema;
  path?: never;
  query?: never;
  url: "/api/games/rooms";
};

export type GamesApiCreateRoomResponses = {
  /**
   * OK
   */
  200: RoomSchema;
};

export type GamesApiCreateRoomResponse =
  GamesApiCreateRoomResponses[keyof GamesApiCreateRoomResponses];

export type GamesApiCreateRoomAsyncData = {
  body: CreateRoomSchema;
  path?: never;
  query?: never;
  url: "/api/games/rooms-async";
};

export type GamesApiCreateRoomAsyncResponses = {
  /**
   * OK
   */
  200: RoomSchema;
};

export type GamesApiCreateRoomAsyncResponse =
  GamesApiCreateRoomAsyncResponses[keyof GamesApiCreateRoomAsyncResponses];

export type GamesApiGetRoomData = {
  body?: never;
  path: {
    /**
     * Room Id
     */
    room_id: number;
  };
  query?: never;
  url: "/api/games/rooms/{room_id}";
};

export type GamesApiGetRoomResponses = {
  /**
   * OK
   */
  200: RoomSchema;
};

export type GamesApiGetRoomResponse =
  GamesApiGetRoomResponses[keyof GamesApiGetRoomResponses];

export type GamesApiCreateRandomSingleplayerRoomData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Data
     */
    data: string;
  };
  url: "/api/games/quick-play";
};

export type GamesApiCreateRandomSingleplayerRoomResponses = {
  /**
   * OK
   */
  200: RoomSchema;
};

export type GamesApiCreateRandomSingleplayerRoomResponse =
  GamesApiCreateRandomSingleplayerRoomResponses[keyof GamesApiCreateRandomSingleplayerRoomResponses];

export type GamesApiCheckGameData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Data
     */
    data: string;
  };
  url: "/api/games/check";
};

export type GamesApiCheckGameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: string;
};
