// This file is auto-generated by @hey-api/openapi-ts

export const MeResponseSchema = {
  properties: {
    id: {
      title: "Id",
      type: "integer",
    },
    email: {
      title: "Email",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
  },
  required: ["id", "email", "username"],
  title: "MeResponse",
  type: "object",
} as const;

export const UserResponseSchema = {
  properties: {
    id: {
      title: "Id",
      type: "integer",
    },
    email: {
      title: "Email",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
  },
  required: ["id", "email", "username"],
  title: "UserResponse",
  type: "object",
} as const;

export const AuthResponseSchema = {
  properties: {
    token: {
      title: "Token",
      type: "string",
    },
    expiry: {
      title: "Expiry",
      type: "string",
    },
  },
  required: ["token", "expiry"],
  title: "AuthResponse",
  type: "object",
} as const;

export const UserLoginSchema = {
  properties: {
    email: {
      format: "email",
      title: "Email",
      type: "string",
    },
    password: {
      title: "Password",
      type: "string",
    },
  },
  required: ["email", "password"],
  title: "UserLogin",
  type: "object",
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      format: "email",
      title: "Email",
      type: "string",
    },
    username: {
      title: "Username",
      type: "string",
    },
    password: {
      title: "Password",
      type: "string",
    },
  },
  required: ["email", "username", "password"],
  title: "UserCreate",
  type: "object",
} as const;
