// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  UserapiMeAf7Faa18Data,
  UserapiMeAf7Faa18Responses,
  UserapiListUsers0Fc0C8F4Data,
  UserapiListUsers0Fc0C8F4Responses,
  UserapiGetUser026Ba149Data,
  UserapiGetUser026Ba149Responses,
  AuthapiLogin0E3Fda03Data,
  AuthapiLogin0E3Fda03Responses,
  AuthapiSignup359681EdData,
  AuthapiSignup359681EdResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Me
 * Get current user profile
 */
export const userapiMeAf7Faa18 = <ThrowOnError extends boolean = false>(
  options?: Options<UserapiMeAf7Faa18Data, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    UserapiMeAf7Faa18Responses,
    unknown,
    ThrowOnError
  >({
    url: "/api/users/me",
    ...options,
  });
};

/**
 * List Users
 * List all users
 */
export const userapiListUsers0Fc0C8F4 = <ThrowOnError extends boolean = false>(
  options?: Options<UserapiListUsers0Fc0C8F4Data, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    UserapiListUsers0Fc0C8F4Responses,
    unknown,
    ThrowOnError
  >({
    url: "/api/users/",
    ...options,
  });
};

/**
 * Get User
 * Get user by ID
 */
export const userapiGetUser026Ba149 = <ThrowOnError extends boolean = false>(
  options: Options<UserapiGetUser026Ba149Data, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    UserapiGetUser026Ba149Responses,
    unknown,
    ThrowOnError
  >({
    url: "/api/users/{user_id}",
    ...options,
  });
};

/**
 * Login
 * Login user with email and password
 */
export const authapiLogin0E3Fda03 = <ThrowOnError extends boolean = false>(
  options: Options<AuthapiLogin0E3Fda03Data, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthapiLogin0E3Fda03Responses,
    unknown,
    ThrowOnError
  >({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Signup
 * Register new user
 */
export const authapiSignup359681Ed = <ThrowOnError extends boolean = false>(
  options: Options<AuthapiSignup359681EdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthapiSignup359681EdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/auth/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
