// This file is auto-generated by @hey-api/openapi-ts

/**
 * MeResponse
 */
export type MeResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
};

/**
 * AuthResponse
 */
export type AuthResponse = {
  /**
   * Token
   */
  token: string;
  /**
   * Expiry
   */
  expiry: string;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Username
   */
  username: string;
  /**
   * Password
   */
  password: string;
};

export type UserapiMeAf7Faa18Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/me";
};

export type UserapiMeAf7Faa18Responses = {
  /**
   * OK
   */
  200: MeResponse;
};

export type UserapiMeAf7Faa18Response =
  UserapiMeAf7Faa18Responses[keyof UserapiMeAf7Faa18Responses];

export type UserapiListUsers0Fc0C8F4Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/users/";
};

export type UserapiListUsers0Fc0C8F4Responses = {
  /**
   * Response
   * OK
   */
  200: Array<UserResponse>;
};

export type UserapiListUsers0Fc0C8F4Response =
  UserapiListUsers0Fc0C8F4Responses[keyof UserapiListUsers0Fc0C8F4Responses];

export type UserapiGetUser026Ba149Data = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/api/users/{user_id}";
};

export type UserapiGetUser026Ba149Responses = {
  /**
   * OK
   */
  200: UserResponse;
};

export type UserapiGetUser026Ba149Response =
  UserapiGetUser026Ba149Responses[keyof UserapiGetUser026Ba149Responses];

export type AuthapiLogin0E3Fda03Data = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type AuthapiLogin0E3Fda03Responses = {
  /**
   * OK
   */
  200: AuthResponse;
};

export type AuthapiLogin0E3Fda03Response =
  AuthapiLogin0E3Fda03Responses[keyof AuthapiLogin0E3Fda03Responses];

export type AuthapiSignup359681EdData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/api/auth/signup";
};

export type AuthapiSignup359681EdResponses = {
  /**
   * OK
   */
  200: AuthResponse;
};

export type AuthapiSignup359681EdResponse =
  AuthapiSignup359681EdResponses[keyof AuthapiSignup359681EdResponses];

export type ClientOptions = {
  baseUrl: string;
};
